/**
 * Full franchise names per league, used as routing aliases so a question that
 * names a team ("Miami Heat") routes to its league's skill even without the
 * league name. Full names only: nicknames like "Heat" or "Kings" are ambiguous
 * across leagues and ordinary words, and single-word names ("Athletics") are
 * skipped for the same reason.
 *
 * Generated 2026-09-23 from sports-skills `<league>.get_teams()` (ESPN) at
 * sports-skills 53e949e. Regenerate when franchises move or rename.
 */
export const TEAM_ALIASES: Readonly<Record<string, readonly string[]>> = {
  nba: [
    "atlanta hawks",
    "boston celtics",
    "brooklyn nets",
    "charlotte hornets",
    "chicago bulls",
    "cleveland cavaliers",
    "dallas mavericks",
    "denver nuggets",
    "detroit pistons",
    "golden state warriors",
    "houston rockets",
    "indiana pacers",
    "la clippers",
    "los angeles lakers",
    "memphis grizzlies",
    "miami heat",
    "milwaukee bucks",
    "minnesota timberwolves",
    "new orleans pelicans",
    "new york knicks",
    "oklahoma city thunder",
    "orlando magic",
    "philadelphia 76ers",
    "phoenix suns",
    "portland trail blazers",
    "sacramento kings",
    "san antonio spurs",
    "toronto raptors",
    "utah jazz",
    "washington wizards",
  ],
  wnba: [
    "atlanta dream",
    "chicago sky",
    "connecticut sun",
    "dallas wings",
    "golden state valkyries",
    "indiana fever",
    "las vegas aces",
    "los angeles sparks",
    "minnesota lynx",
    "new york liberty",
    "phoenix mercury",
    "portland fire",
    "seattle storm",
    "toronto tempo",
    "washington mystics",
  ],
  nfl: [
    "arizona cardinals",
    "atlanta falcons",
    "baltimore ravens",
    "buffalo bills",
    "carolina panthers",
    "chicago bears",
    "cincinnati bengals",
    "cleveland browns",
    "dallas cowboys",
    "denver broncos",
    "detroit lions",
    "green bay packers",
    "houston texans",
    "indianapolis colts",
    "jacksonville jaguars",
    "kansas city chiefs",
    "las vegas raiders",
    "los angeles chargers",
    "los angeles rams",
    "miami dolphins",
    "minnesota vikings",
    "new england patriots",
    "new orleans saints",
    "new york giants",
    "new york jets",
    "philadelphia eagles",
    "pittsburgh steelers",
    "san francisco 49ers",
    "seattle seahawks",
    "tampa bay buccaneers",
    "tennessee titans",
    "washington commanders",
  ],
  mlb: [
    "arizona diamondbacks",
    "atlanta braves",
    "baltimore orioles",
    "boston red sox",
    "chicago cubs",
    "chicago white sox",
    "cincinnati reds",
    "cleveland guardians",
    "colorado rockies",
    "detroit tigers",
    "houston astros",
    "kansas city royals",
    "los angeles angels",
    "los angeles dodgers",
    "miami marlins",
    "milwaukee brewers",
    "minnesota twins",
    "new york mets",
    "new york yankees",
    "philadelphia phillies",
    "pittsburgh pirates",
    "san diego padres",
    "san francisco giants",
    "seattle mariners",
    "st. louis cardinals",
    "tampa bay rays",
    "texas rangers",
    "toronto blue jays",
    "washington nationals",
  ],
  nhl: [
    "anaheim ducks",
    "boston bruins",
    "buffalo sabres",
    "calgary flames",
    "carolina hurricanes",
    "chicago blackhawks",
    "colorado avalanche",
    "columbus blue jackets",
    "dallas stars",
    "detroit red wings",
    "edmonton oilers",
    "florida panthers",
    "los angeles kings",
    "minnesota wild",
    "montreal canadiens",
    "nashville predators",
    "new jersey devils",
    "new york islanders",
    "new york rangers",
    "ottawa senators",
    "philadelphia flyers",
    "pittsburgh penguins",
    "san jose sharks",
    "seattle kraken",
    "st. louis blues",
    "tampa bay lightning",
    "toronto maple leafs",
    "utah mammoth",
    "vancouver canucks",
    "vegas golden knights",
    "washington capitals",
    "winnipeg jets",
  ],
};
